name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
# Ensure only one run of this workflow executes at a time, but don't auto-cancel.
concurrency:
  group: root-deployment-${{ github.ref }}
  cancel-in-progress: false

jobs:
  guard:
    uses: ./.github/workflows/cancel-obsolete.yml

  dummy_long_job:
    name: Dummy 1-minute job
    needs: guard
    runs-on: ubuntu-latest
    steps:
      - name: Print start time
        run: echo "Dummy job started at $(date -u)"

      - name: Sleep for 1 minute # test
        run: sleep 60

      - name: Print end time
        run: echo "Dummy job finished at $(date -u)"
 